// <auto-generated />
using System;
using JouleadAssistantDesign.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JouleadAssistantDesign.Migrations
{
    [DbContext(typeof(JouleadDbContext))]
    [Migration("20250813090703_AddImagePathsToTemplateElement")]
    partial class AddImagePathsToTemplateElement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("JouleadAssistantDesign.Models.CustomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomItems");
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.ElementConfig", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "CustomItemId", "Id");

                    b.ToTable("ElementConfigs");
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HandoverDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomItemId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.TemplateElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DropdownOptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePaths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDropdownEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateItemId");

                    b.ToTable("TemplateElements");
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.TemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TemplateItems");
                });

            modelBuilder.Entity("ProjectTemplateItem", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedItemsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectsId", "SelectedItemsId");

                    b.HasIndex("SelectedItemsId");

                    b.ToTable("ProjectTemplateItems", (string)null);
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.ElementConfig", b =>
                {
                    b.HasOne("JouleadAssistantDesign.Models.Project", "Project")
                        .WithMany("ElementConfigs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.Project", b =>
                {
                    b.HasOne("JouleadAssistantDesign.Models.CustomItem", null)
                        .WithMany("Projects")
                        .HasForeignKey("CustomItemId");
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.TemplateElement", b =>
                {
                    b.HasOne("JouleadAssistantDesign.Models.TemplateItem", "TemplateItem")
                        .WithMany("Elements")
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("ProjectTemplateItem", b =>
                {
                    b.HasOne("JouleadAssistantDesign.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JouleadAssistantDesign.Models.TemplateItem", null)
                        .WithMany()
                        .HasForeignKey("SelectedItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.CustomItem", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.Project", b =>
                {
                    b.Navigation("ElementConfigs");
                });

            modelBuilder.Entity("JouleadAssistantDesign.Models.TemplateItem", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
